#!/bin/bash
#a simple password generator
#by looneytkp
set -xe
e=echo
getpasswd=google.com/cr
#line=$1|$2|$3|$4|$5
shopt -u nocasematch
case $1 in
    "") if [ ! -e ~/.genfile ]; then
          touch ~/.genfile
        fi
        $e && $e "ps: works with internet."
        $e "enter name of the site/file you wanna generate a password for."
        read -p "Name: " name
        if grep -q "$name" ~/.genfile
          then
              sed_name=$(grep $name ~/.genfile > ~/.genfile2 | sed "s-$name: --" ~/.genfile2 && rm ~/.genfile2)
              $e "password for $name exists -> [ $sed_name ]"
              read -p "wanna update the password? <y/n> #? " pswd
              case $pswd in
                  y) password=$(curl -s $getpasswd)
                     sed -i "s/$name: .*/$name: $password/g" ~/.genfile
                     grep_name2=$(grep $name ~/.genfile)
                     $e "previous password -> $grep_name"
                     $e "new password -> $grep_name2" && $e;;
                  n) $e "Ok...";;
              esac
          else
              password=$(curl -s $getpasswd)
              $e "password for $name is: $password" && $e "$name: $password" >> ~/.genfile
              $e
        fi;;
    "-s") $e && read -p "search for saved passwords: " search
          if grep "$search" ~/.genfile > /dev/null
            then
                grep "$search" ~/.genfile > ~/.genfile2
                edit=$(sed "s_$search: __" ~/.genfile2)
                $e "password: $edit"
                rm ~/.genfile2
                $e
            else
                $e
                $e "cannot find $search in the list of saved passwords"
                $e 'type "genfile -l" to list saved passwords' && $e
          fi;;
    "-l") if [ -e ~/.genfile ]; then
	    $e "list of saved passwords:" && $e
	    cat ~/.genfile && $e
	    else
   	        $e "no passwords have been saved"
 	  fi;;
    *) if [ ! -e ~/.genfile ]; then
  touch ~/.genfile
fi
$e && $e "ps: works with internet."
  one=$(grep $1 ~/.genfile)
if [ $one = 0 ]  #> /dev/null
         then
             grepp=$(grep $1 ~/.genfile > ~/.genfile2 | sed "s-$1: --" ~/.genfile2)
             $e "password for $1 exists -> [ $sed_name ]"
             read -p "wanna update the password? <y/n> #? " pswd
             case $pswd in
                 y) password=$(curl -s $getpasswd)
                    sed -i "s/$1: .*/$1: $password/g" ~/.genfile
                    grep_name2=$(grep $1 ~/.genfile)
                    $e "previous password -> $grep_name"
                    $e "new password -> $grep_name2" && $e;;
                 n) $e "exited...";;
             esac
         elif [ $one = 1 ]
             then
             password=$(curl -s $getpasswd)
             $e "password for $1 is: $password" && $e "$1: $password" >> ~/.genfile
             $e
         else 
             echo "nice"
fi;;
esac
