#!/bin/bash
#a simple password generator
#by looneytkp
set -xe
e=echo
getpasswd=google.com/cr
#line=$1|$2|$3|$4|$5
shopt -u nocasematch
case $1 in
    "") $e && $e "ps: Works with internet."
        $e "Enter name of the site/file you wanna generate a password for."
        read -p "Name: " name
        if grep "$name" ~/.genpass > /dev/null
          then
              sed_name=$(grep $name ~/.genpass > ~/.genpass2 | sed "s-$name: --" ~/.genpass2 && rm ~/.genpass2)
              $e "password for $name exists -> [ $sed_name ]"
              read -p "Wanna update the password? <y/n> #? " pswd
              case $pswd in
                  y) password=$(curl -s $getpasswd)
                     sed -i "s/$name: .*/$name: $password/g" ~/.genpass
                     grep_name2=$(grep $name ~/.genpass)
                     $e "Previous password -> $grep_name"
                     $e "New password -> $grep_name2" && $e;;
                  n) $e "Ok...";;
              esac
          else
              password=$(curl -s $getpasswd)
              $e "Password for $name is: $password" && $e "$name: $password" >> ~/.genpass
              $e
        fi;;
    "-s") $e && read -p "search for saved passwords: " search
          if grep "$search" ~/.genpass > /dev/null
            then
                grep "$search" ~/.genpass > ~/.genpass2
                edit=$(sed "s_$search: __" ~/.genpass2)
                $e "Password: $edit"
                rm ~/.genpass2
                $e
            else
                $e
                $e "Cannot find $search in the list of saved passwords"
                $e 'type "genpass -l" to list saved passwords' && $e
          fi;;
    "-l") if [ -e ~/.genpass ]; then
	    $e "list of saved passwords:" && $e
	    cat ~/.genpass && $e
	    else
   	        $e "no passwords have been saved"
 	  fi;;
    *) $e && $e "ps: Works with internet."
  one=$(grep $1 ~/.genpass)
if [ $one = 0 ]  #> /dev/null
         then
             grepp=$(grep $1 ~/.genpass > ~/.genpass2 | sed "s-$1: --" ~/.genpass2)
             $e "password for $1 exists -> [ $sed_name ]"
             read -p "Wanna update the password? <y/n> #? " pswd
             case $pswd in
                 y) password=$(curl -s $getpasswd)
                    sed -i "s/$1: .*/$1: $password/g" ~/.genpass
                    grep_name2=$(grep $1 ~/.genpass)
                    $e "Previous password -> $grep_name"
                    $e "New password -> $grep_name2" && $e;;
                 n) $e "Ok...";;
             esac
         elif [ $one = 1 ]
             then
             password=$(curl -s $getpasswd)
             $e "Password for $1 is: $password" && $e "$1: $password" >> ~/.genpass
             $e
         else 
             echo "nice"
fi;;
esac
