#!/bin/bash
set -e
shopt -u nocasematch

short() {
    </dev/urandom tr -dc '9538207164!@#?$%DJALGSKHFqwertypoiuMZNXBCVfldkahjsPQOWEIRUTY' | head -c8; $e ""
}
long() {
    strings /dev/urandom | grep -o '[[:alnum:]]' | head -n 30 | tr -d '\n'; $e
}

#if [ ! -e /usr/bin/mkpwd ]; then echo "mkpwd is not installed.";fi

case "$1" in
    "")
        echo "info";;

    -l|-s)
        if [ $1 == -l ]; then echo "long"
        fi
esac
